const dummyData = [
  {
      "id": 1,
      "name": "Lindsay Ledner AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/log-cabin-1886620_640.jpg",
      "home_type": "mansion",
      "beds": 12,
      "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
      "city": "palo alto",
      "cost_per_night": 34,
      "reviews": 131,
      "avg_rating": 2.01,
      "isSuperhost": 0
  },
  {
      "id": 2,
      "name": "Ronnie Prosacco AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/architecture-2804083_640.jpg",
      "home_type": "cabin",
      "beds": 1,
      "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
      "city": "san carlos",
      "cost_per_night": 39,
      "reviews": 22,
      "avg_rating": 1.81,
      "isSuperhost": 1
  },
  {
      "id": 3,
      "name": "Marian Kuhic AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/fishermen-cabin-1191186_640.jpg",
      "home_type": "hut",
      "beds": 3,
      "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
      "city": "half moon bay",
      "cost_per_night": 25,
      "reviews": 433,
      "avg_rating": 3.9,
      "isSuperhost": 0
  },
  {
      "id": 4,
      "name": "Corey Flatley AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/mountains-2154198_640.jpg",
      "home_type": "mansion",
      "beds": 6,
      "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
      "city": "pescadero",
      "cost_per_night": 30,
      "reviews": 712,
      "avg_rating": 3.45,
      "isSuperhost": 1
  },
  {
      "id": 5,
      "name": "Miss Roberta Rau AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/interior-1961070_640.jpg",
      "home_type": "apartment",
      "beds": 5,
      "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
      "city": "pescadero",
      "cost_per_night": 36,
      "reviews": 899,
      "avg_rating": 1.9,
      "isSuperhost": 1
  },
  {
      "id": 6,
      "name": "Mr. Luther McCullough AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/life-863016_640.jpg",
      "home_type": "mansion",
      "beds": 12,
      "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
      "city": "la honda",
      "cost_per_night": 37,
      "reviews": 409,
      "avg_rating": 4.51,
      "isSuperhost": 0
  },
  {
      "id": 7,
      "name": "Phyllis Paucek AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/log-cabin-1886620_640.jpg",
      "home_type": "apartment",
      "beds": 2,
      "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
      "city": "san carlos",
      "cost_per_night": 49,
      "reviews": 47,
      "avg_rating": 4.94,
      "isSuperhost": 0
  },
  {
      "id": 8,
      "name": "Jessie Hills DDS AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/log-cabin-1594361_640.jpg",
      "home_type": "igloo",
      "beds": 1,
      "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
      "city": "la honda",
      "cost_per_night": 11,
      "reviews": 740,
      "avg_rating": 3.37,
      "isSuperhost": 1
  },
  {
      "id": 9,
      "name": "Ms. Camille Stehr AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/fishermen-cabin-1191186_640.jpg",
      "home_type": "cabin",
      "beds": 9,
      "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
      "city": "half moon bay",
      "cost_per_night": 15,
      "reviews": 850,
      "avg_rating": 3.74,
      "isSuperhost": 0
  },
  {
      "id": 10,
      "name": "Tracy Fay AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/norway-2708286_640.jpg",
      "home_type": "hut",
      "beds": 9,
      "description": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
      "city": "palo alto",
      "cost_per_night": 39,
      "reviews": 671,
      "avg_rating": 4.57,
      "isSuperhost": 1
  },
  {
      "id": 11,
      "name": "Elias Conroy AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/log-cabin-1594361_640.jpg",
      "home_type": "mansion",
      "beds": 6,
      "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
      "city": "half moon bay",
      "cost_per_night": 44,
      "reviews": 157,
      "avg_rating": 1.29,
      "isSuperhost": 1
  },
  {
      "id": 12,
      "name": "Whitney Harber AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/fishermen-cabin-1191186_640.jpg",
      "home_type": "apartment",
      "beds": 8,
      "description": "The Football Is Good For Training And Recreational Purposes",
      "city": "san carlos",
      "cost_per_night": 38,
      "reviews": 237,
      "avg_rating": 3.42,
      "isSuperhost": 0
  },
  {
      "id": 13,
      "name": "Faye Veum AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/holiday-house-177401_640.jpg",
      "home_type": "hotel",
      "beds": 1,
      "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
      "city": "pescadero",
      "cost_per_night": 24,
      "reviews": 901,
      "avg_rating": 2.28,
      "isSuperhost": 0
  },
  {
      "id": 14,
      "name": "Eva Quigley AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/apartment-3564955_640.jpg",
      "home_type": "apartment",
      "beds": 3,
      "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
      "city": "san carlos",
      "cost_per_night": 22,
      "reviews": 188,
      "avg_rating": 4.25,
      "isSuperhost": 0
  },
  {
      "id": 15,
      "name": "Sam Gutkowski AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/log-cabin-1594361_640.jpg",
      "home_type": "mansion",
      "beds": 5,
      "description": "The Football Is Good For Training And Recreational Purposes",
      "city": "menlo park",
      "cost_per_night": 38,
      "reviews": 437,
      "avg_rating": 4.74,
      "isSuperhost": 1
  },
  {
      "id": 16,
      "name": "Alfonso Moore AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/fishermen-cabin-1191186_640.jpg",
      "home_type": "apartment",
      "beds": 3,
      "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
      "city": "palo alto",
      "cost_per_night": 10,
      "reviews": 722,
      "avg_rating": 1.16,
      "isSuperhost": 1
  },
  {
      "id": 17,
      "name": "Justin Kohler AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/ivy-529767_640.jpg",
      "home_type": "home",
      "beds": 3,
      "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
      "city": "pescadero",
      "cost_per_night": 40,
      "reviews": 230,
      "avg_rating": 2.28,
      "isSuperhost": 0
  },
  {
      "id": 18,
      "name": "Doug Shields AirBnB",
      "img_url": "https://aquabnblistingimages.s3-us-west-1.amazonaws.com/home_images/architecture-1834813_640.jpg",
      "home_type": "cabin",
      "beds": 8,
      "description": "The Football Is Good For Training And Recreational Purposes",
      "city": "pescadero",
      "cost_per_night": 40,
      "reviews": 919,
      "avg_rating": 1.27,
      "isSuperhost": 1
  }
];
export default dummyData;